# This is a basic workflow to help you get started with# Run Ceedling tests

name: Ceedling

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master, action ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "unit-test"
  unit-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2      
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Install Ceedling
      run: gem install ceedling

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
    #To continue: sudo touch /continue

    - name: Go to fsm_rebound folder
      run: cd fsm_rebound

    - name: Do testing
      run: |
        ceedling test:all
